export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const DOWNLOAD_PRODUCTS = "DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESSFUL = "DOWNLOAD_PRODUCTS_SUCCESSFUL";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
