export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
