export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const DOWNLOAD_PRODUCTS = "DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESSFUL = "DOWNLOAD_PRODUCTS_SUCCESSFUL";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";
export const DELETE_PRODUCT_SUCCESSFUL = "DELETE_PRODUCT_SUCCESSFUL";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
export const GET_PRODUCT_TO_EDIT = "GET_PRODUCT_TO_EDIT";
export const UPDATE_PRODUCT_SUCCESSFUL = "UPDATE_PRODUCT_SUCCESSFUL";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
